movesense sensor data from whiteboard api
holmmi/Movesense pull request #19
Opened 2022-03-31 08:49 UTC by tiitustelke

2022-03-31 15:17 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseConnector.kt
> +    }
Eikö `private val mds: Mds = Mds.builder().build(context)` toiminut?

2022-03-31 15:19 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/navigation/Navigation.kt
> +                        MeasureView(navController, device)
Miksi koko laite-olio pitää viedä näkymään, jos pelkkä MAC-osoite riittää yhdistämiseen?

2022-03-31 15:21 UTC, holmmi requested changes
Hyvä, muutamia kohtia kommentoin ja laitoin kysymyksiä.

2022-04-01 07:28 UTC, tiitustelke commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseConnector.kt
> +    }
laitoin tolla tavalla, koska esimerkissäkin oli. Näyttäisi toimivan myös kirjoittamallasi tavalla, niin vaihdan noin.

2022-04-01 07:29 UTC, tiitustelke commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseConnector.kt
> +        private val SCHEME_PREFIX = "suunto://";
hyvä huomio

2022-04-01 07:31 UTC, tiitustelke commented on app/src/main/java/fi/metropolia/movesense/navigation/Navigation.kt
> +                        MeasureView(navController, device)
sekaannuin siitä kun datan saaminen vaati serialin, niin aattelin että pitää sitten lähettää enemmän dataa kun pelkkä mac. Serialin saikin kuitenkin yhdistämisen jälkeen ja argumentti jäi tollaiseksi. Vaihdan pelkäksi stringiksi.

2022-04-01 07:32 UTC, tiitustelke commented
Refactoroin ja parantelin vähän. Laitan uuden requestin.

2022-04-04 04:09 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseConnector.kt
> +            Log.e("btstatus", "connect exception ${e.localizedMessage}")
Tuossa lokituksen ensimmäisessä parametrissä voisi käyttää luokan nimeä. Esimerkiksi companion objectiin voisi luoda `TAG`-muuttujan, joka saisi arvokseen `MovesenseConnector.simpleName` tms. ja sitten käyttää tuota `TAG` muuttujaa lokituksissa.

2022-04-04 04:09 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseConnector.kt
> +            Log.e("btstatus", "connect exception ${e.localizedMessage}")
Tuossa lokituksen ensimmäisessä parametrissä voisi käyttää luokan nimeä. Esimerkiksi companion objectiin voisi luoda `TAG`-muuttujan, joka saisi arvokseen `MovesenseConnector.simpleName` tms. ja sitten käyttää tuota `TAG` muuttujaa lokituksissa.

2022-04-04 04:12 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/navigation/Navigation.kt
> +    const val MEASURE = "measure/{address}"
Bottom navigation ei taida näyttää tässä tapauksessa aktiivista tabia. Olisi hyvä säätää se niin, että start olisi aktiivinen, koska sieltä navigoidaan kuitenkin mittausnäkymään.

2022-04-04 04:12 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/navigation/Navigation.kt
> +    const val MEASURE = "measure/{address}"
Bottom navigation ei taida näyttää tässä tapauksessa aktiivista tabia. Olisi hyvä säätää se niin, että start olisi aktiivinen, koska sieltä navigoidaan kuitenkin mittausnäkymään.

2022-04-04 04:13 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseDevice.kt
> +@Parcelize
Pitääkö olla vielä parceloitu, jos seuraavaan näkymään viedään vain laitteen osoite merkkijonona?

2022-04-04 04:13 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseDevice.kt
> +@Parcelize
Pitääkö olla vielä parceloitu, jos seuraavaan näkymään viedään vain laitteen osoite merkkijonona?

2022-04-04 04:15 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/view/measure/MeasureViewModel.kt
> +                    "btstatus",
Näissäkin lokituksissa voisi päteä sama kuin edellä.

2022-04-04 04:15 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/view/measure/MeasureViewModel.kt
> +                    "btstatus",
Näissäkin lokituksissa voisi päteä sama kuin edellä.

2022-04-04 04:17 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/model/DataResponse.kt
> +class DataResponse(@field:SerializedName("Body") val body: Body) {
Olisiko luokalle ja tiedostolle parempi nimi `MovesenseDataResponse`? Pohdin, että `DataResponse` on aika geneerinen, jos tulee muita samanlaisia tapauksia.

2022-04-04 04:17 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/model/DataResponse.kt
> +class DataResponse(@field:SerializedName("Body") val body: Body) {
Olisiko luokalle ja tiedostolle parempi nimi `MovesenseDataResponse`? Pohdin, että `DataResponse` on aika geneerinen, jos tulee muita samanlaisia tapauksia.

2022-04-04 04:19 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseConnector.kt
> +            sb.append("{\"Uri\": \"").append(serial).append(URI_MEAS_IMU_9).append("\"}")
Tätä riviä voisi siivota laittamalla jokainen `append` omalle rivilleen.

2022-04-04 04:19 UTC, holmmi commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseConnector.kt
> +            sb.append("{\"Uri\": \"").append(serial).append(URI_MEAS_IMU_9).append("\"}")
Tätä riviä voisi siivota laittamalla jokainen `append` omalle rivilleen.

2022-04-04 04:20 UTC, holmmi commented on app/build.gradle
> +    id 'kotlin-parcelize'
Tämän voi poistaa, jos parceloituja luokkia ei enää tarvita.

2022-04-04 04:20 UTC, holmmi commented on app/build.gradle
> +    id 'kotlin-parcelize'
Tämän voi poistaa, jos parceloituja luokkia ei enää tarvita.

2022-04-04 04:21 UTC, holmmi reviewed
Hyvältä näyttää. Muutama asia katsottavaksi.

2022-04-04 04:24 UTC, holmmi commented
Sori, jostakin syystä noita katselmointikommentteja on tullut nyt tuplasti 😁

2022-04-04 08:43 UTC, tiitustelke commented on app/build.gradle
> +    id 'kotlin-parcelize'
joo taisin sen uudemmassa branchissa poistaakin, mutta poistan vielä täältä.

2022-04-04 08:44 UTC, tiitustelke commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseConnector.kt
> +            sb.append("{\"Uri\": \"").append(serial).append(URI_MEAS_IMU_9).append("\"}")
👍

2022-04-04 08:47 UTC, tiitustelke commented on app/src/main/java/fi/metropolia/movesense/model/DataResponse.kt
> +class DataResponse(@field:SerializedName("Body") val body: Body) {
ihan hyvä idis

2022-04-04 08:49 UTC, tiitustelke commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseDevice.kt
> +@Parcelize
Joo huomasin toisessa branchissa, että noi unohtui. Poistan nää vielä täältä.

2022-04-04 08:51 UTC, tiitustelke commented on app/src/main/java/fi/metropolia/movesense/bluetooth/MovesenseConnector.kt
> +            Log.e("btstatus", "connect exception ${e.localizedMessage}")
👍

2022-04-04 09:09 UTC, merged